import { defineConfig } from 'vitepress'
import katexModernPlugin from './plugins/katex-modern.mjs'
import wikiLinksPlugin from './plugins/wiki-links.mjs'
// AUTO-GENERATED sidebar — re-generated by gen-sidebar.mjs on every build
import { generatedSidebar } from './_sidebar-generated.mjs'

export default defineConfig({
  title: 'Hermes',
  srcDir: 'src',
  outDir: 'dist',
  base: '/wiki/',
  router: {
    prefetchLinks: false,
  },
  ignoreDeadLinks: true,

  markdown: {
    config: (md) => {
      md.use(katexModernPlugin)
      md.use(wikiLinksPlugin)
    },
  },

  head: [
    ['link', { rel: 'stylesheet', href: '/wiki/assets/katex.min.css' }],
    ['link', { rel: 'icon', href: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y=".9em" font-size="90">📚</text></svg>' }],
  ],

  themeConfig: {
    sidebar: generatedSidebar,

    nav: [],

    search: false,
  }
})
