#!/usr/bin/env node
/**
 * gen-sidebar.mjs
 * Auto-generates the VitePress sidebar config from src/ directory structure.
 * Produces a JSON-compatible snippet that gets merged into config.ts.
 *
 * Run manually: node .vitepress/gen-sidebar.mjs
 * Run in CI/build: node .vitepress/gen-sidebar.mjs && vitepress build .
 */

import { readdir, stat, readFile } from 'fs/promises'
import { join, extname, basename } from 'path'
import { existsSync, writeFileSync } from 'fs'

const SRC = join(process.cwd(), 'src')
const OUT = join(process.cwd(), '.vitepress', '_sidebar-generated.mjs')

// Section order for the sidebar
const SECTION_ORDER = ['concepts', 'entities', 'comparisons', 'queries', 'raw']

// Files to skip (not shown in sidebar)
const SKIP_FILES = new Set(['index.md', 'log.md', 'SCHEMA.md'])

// Extensions to treat as pages
const PAGE_EXTENSIONS = new Set(['.md'])

function walkDir(dir, baseDir = dir) {
  return readdir(dir).then(async (entries) => {
    const items = []
    for (const entry of entries.sort()) {
      if (entry.startsWith('.') || entry === '_archive' || entry === '_meta') continue
      const fullPath = join(dir, entry)
      const relPath = fullPath.replace(baseDir + '/', '').replace(baseDir, '')

      const s = await stat(fullPath)
      if (s.isDirectory()) {
        const children = await walkDir(fullPath, baseDir)
        if (children.length > 0) {
          items.push({
            text: formatLabel(entry),
            collapsed: true,
            items: children,
          })
        }
      } else if (s.isFile()) {
        const ext = extname(entry)
        const name = basename(entry, ext)
        if (PAGE_EXTENSIONS.has(ext) && !SKIP_FILES.has(entry)) {
          // frontmatter title override check
          const title = await getFrontmatterTitle(fullPath) || formatLabel(name)
          items.push({
            text: title,
            link: '/' + relPath.replace(/\\/g, '/').replace(/\.md$/, ''),
          })
        }
      }
    }
    return items
  })
}

function formatLabel(name) {
  return name
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

async function getFrontmatterTitle(filePath) {
  try {
    const content = await readFile(filePath, 'utf-8')
    const match = content.match(/^---\ntitle:\s*(.+)\n/)
    if (match) return match[1].trim().replace(/^["']|["']$/g, '')
  } catch {}
  return null
}

function sortBySectionOrder(items) {
  return items.sort((a, b) => {
    const aKey = a.link?.replace('/', '').split('/')[0] || ''
    const bKey = b.link?.replace('/', '').split('/')[0] || ''
    const aIdx = SECTION_ORDER.indexOf(aKey)
    const bIdx = SECTION_ORDER.indexOf(bKey)
    if (aIdx === -1 && bIdx === -1) return a.text.localeCompare(b.text)
    if (aIdx === -1) return 1
    if (bIdx === -1) return -1
    return aIdx - bIdx
  })
}

async function buildSidebar() {
  if (!existsSync(SRC)) {
    console.error(`Source dir not found: ${SRC}`)
    process.exit(1)
  }

  const entries = await readdir(SRC)
  const sections = []

  for (const entry of entries) {
    if (entry.startsWith('.') || entry === '_archive' || entry === '_meta') continue
    const fullPath = join(SRC, entry)
    const s = await stat(fullPath)

    if (s.isDirectory()) {
      const children = await walkDir(fullPath, SRC)
      if (children.length > 0) {
        sections.push({
          text: formatLabel(entry),
          collapsed: true,
          items: children,
        })
      }
    }
  }

  // Re-sort sections by SECTION_ORDER
  const sorted = sortBySectionOrder(sections)

  // Home section always first
  const homeSection = {
    text: 'Home',
    items: [
      { text: 'Home', link: '/index' },
      { text: 'Graph', link: '/graph' },
      { text: 'Log', link: '/log' },
      { text: 'Schema', link: '/SCHEMA' },
    ],
  }

  const rawSection = sorted.find((s) => s.text === 'Raw')
  const otherSections = sorted.filter((s) => s.text !== 'Raw')

  // Raw always last
  const finalSidebar = [homeSection, ...otherSections]
  if (rawSection) finalSidebar.push(rawSection)

  return finalSidebar
}

buildSidebar().then(async (sidebar) => {
  const output = `// AUTO-GENERATED by .vitepress/gen-sidebar.mjs — do not edit manually
// This file is re-generated on every wiki build or manual run
export const generatedSidebar = ${JSON.stringify(sidebar, null, 2)}
`

  writeFileSync(OUT, output)
  console.log(`[gen-sidebar] Generated sidebar with ${sidebar.reduce((acc, s) => acc + (s.items?.length || 0), 0)} items across ${sidebar.length} sections`)
  console.log(`[gen-sidebar] Output: ${OUT}`)
}).catch((err) => {
  console.error('[gen-sidebar] Error:', err)
  process.exit(1)
})
